# Default values for python-project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: nithish005.azurecr.io/python-webapp
  pullPolicy: IfNotPresent
  tag: "e7c9e82ee30aabea02fe6be1403fea6b59741c50"

service:
  type: ClusterIP
  port: 5000

containerPort: 5000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
